-- 双碳数据
CREATE TABLE TXBBG07 (
	UUID VARCHAR2(32) DEFAULT ' ' NOT NULL,
	REC_CREATOR VARCHAR2(32) DEFAULT ' ' NOT NULL,
	REC_CREATOR_NAME VARCHAR2(100) DEFAULT ' ' NOT NULL,
    REC_CREATE_TIME VARCHAR2(17) DEFAULT ' ' NOT NULL,
	REC_REVISOR VARCHAR2(32) DEFAULT ' ' NOT NULL,
	REC_REVISOR_NAME VARCHAR2(100) DEFAULT ' ' NOT NULL,
	REC_REVISOR_TIME VARCHAR2(17) DEFAULT ' ' NOT NULL,
    ARCHIVE_FLAG VARCHAR2(1) DEFAULT ' ' NOT NULL,
	DEL_FLAG NUMBER(1,0) DEFAULT 0 NOT NULL,
    TENANT_USER VARCHAR(10) DEFAULT ' ' NOT NULL,
	UNIT_CODE VARCHAR(10) DEFAULT ' ' NOT NULL,
	SEG_NO VARCHAR2(10) DEFAULT ' ' NOT NULL,
	RECORD_DATE date NOT NULL,
  	INDICATOR_NAME varchar(128) NOT NULL,
	INDICATOR_ID varchar(32) NOT NULL,
  	INDICATOR_UNIT varchar(32) DEFAULT ' ' NOT NULL,
  	INDICATOR_FREQUENCY varchar(16) NOT NULL,
  	INDICATOR_VALUE varchar(64) NOT NULL,
	INDICATOR_RESOURCE varchar(64) DEFAULT ' ' NOT NULL,
  	INDICATOR_TITLE varchar(255) NOT NULL,
	CONSTRAINT TXBBG07_PK PRIMARY KEY (UUID)
);
COMMENT ON TABLE TXBBG07 IS '分类-双碳数据';
COMMENT ON COLUMN TXBBG07.UUID IS 'ID';
COMMENT ON COLUMN TXBBG07.REC_CREATOR IS '记录创建人';
COMMENT ON COLUMN TXBBG07.REC_CREATOR_NAME IS '记录创建人姓名';
COMMENT ON COLUMN TXBBG07.REC_CREATE_TIME IS '记录创建时间';
COMMENT ON COLUMN TXBBG07.REC_REVISOR IS '记录修改人';
COMMENT ON COLUMN TXBBG07.REC_REVISOR_NAME IS '记录修改人姓名';
COMMENT ON COLUMN TXBBG07.REC_REVISOR_TIME IS '记录修改时间';
COMMENT ON COLUMN TXBBG07.ARCHIVE_FLAG IS '归档标记';
COMMENT ON COLUMN TXBBG07.DEL_FLAG IS '记录删除标记';
COMMENT ON COLUMN TXBBG07.TENANT_USER IS '租户';
COMMENT ON COLUMN TXBBG07.UNIT_CODE IS '业务单元代码';
COMMENT ON COLUMN TXBBG07.SEG_NO IS '系统账套';
COMMENT ON COLUMN TXBBG07.RECORD_DATE IS '数据日期';
COMMENT ON COLUMN TXBBG07.INDICATOR_NAME IS '指标名称';
COMMENT ON COLUMN TXBBG07.INDICATOR_ID IS '指标ID';
COMMENT ON COLUMN TXBBG07.INDICATOR_UNIT IS '指标单位';
COMMENT ON COLUMN TXBBG07.INDICATOR_FREQUENCY IS '指标频度';
COMMENT ON COLUMN TXBBG07.INDICATOR_VALUE IS '指标值';
COMMENT ON COLUMN TXBBG07.INDICATOR_RESOURCE IS '指标来源';
COMMENT ON COLUMN TXBBG07.INDICATOR_TITLE IS '指标来源文件的标题';
